fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        stages: [commit]
  - repo: https://github.com/myint/docformatter
    rev: v1.7.2
    hooks:
      - id: docformatter
        args: [--in-place, --pre-summary-newline, --close-quotes-on-newline]
        stages: [commit]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        stages: [commit]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Check PEP8
        args: [--max-line-length, "88"]
        stages: [commit]
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
    -   id: publish
        name: publish on pypi
        language: system
        entry: publish
        pass_filenames: false
        always_run: true
